# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\RemoteRepo\avdev-v1\avdev-v1\avdev\ui/ui_index.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_index(object):
    def setupUi(self, index):
        index.setObjectName("index")
        index.resize(350, 200)
        index.setMaximumSize(QtCore.QSize(350, 200))
        self.centralwidget = QtWidgets.QWidget(index)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_auto = QtWidgets.QPushButton(self.centralwidget)
        self.btn_auto.setObjectName("btn_auto")
        self.verticalLayout.addWidget(self.btn_auto)
        self.btn_manual = QtWidgets.QPushButton(self.centralwidget)
        self.btn_manual.setObjectName("btn_manual")
        self.verticalLayout.addWidget(self.btn_manual)
        index.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(index)
        self.statusbar.setObjectName("statusbar")
        index.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(index)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 18))
        self.menubar.setObjectName("menubar")
        index.setMenuBar(self.menubar)

        self.retranslateUi(index)
        QtCore.QMetaObject.connectSlotsByName(index)

    def retranslateUi(self, index):
        _translate = QtCore.QCoreApplication.translate
        index.setWindowTitle(_translate("index", "视频标记"))
        self.btn_auto.setText(_translate("index", "违章自动标记"))
        self.btn_manual.setText(_translate("index", "人工确认"))
