# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\远程托管项目\avdev-v1\avdev-v1\avdev\ui/ui_manual.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manual(object):
    def setupUi(self, manual):
        manual.setObjectName("manual")
        manual.resize(654, 264)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        manual.setFont(font)
        self.centralwidget = QtWidgets.QWidget(manual)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.spin = QtWidgets.QSpinBox(self.centralwidget)
        self.spin.setObjectName("spin")
        self.gridLayout.addWidget(self.spin, 0, 1, 1, 1)
        self.slider = QtWidgets.QSlider(self.centralwidget)
        self.slider.setEnabled(True)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.gridLayout.addWidget(self.slider, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_play = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play.setObjectName("btn_play")
        self.gridLayout_2.addWidget(self.btn_play, 0, 0, 1, 1)
        self.btn_unmark = QtWidgets.QPushButton(self.centralwidget)
        self.btn_unmark.setObjectName("btn_unmark")
        self.gridLayout_2.addWidget(self.btn_unmark, 0, 2, 1, 1)
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setObjectName("btn_save")
        self.gridLayout_2.addWidget(self.btn_save, 0, 3, 1, 1)
        self.btn_mark = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mark.setObjectName("btn_mark")
        self.gridLayout_2.addWidget(self.btn_mark, 0, 1, 1, 1)
        self.btn_unsave = QtWidgets.QPushButton(self.centralwidget)
        self.btn_unsave.setObjectName("btn_unsave")
        self.gridLayout_2.addWidget(self.btn_unsave, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_open_raw_video = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_raw_video.setObjectName("btn_open_raw_video")
        self.gridLayout_3.addWidget(self.btn_open_raw_video, 0, 0, 1, 1)
        self.btn_open_auto_video = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_auto_video.setObjectName("btn_open_auto_video")
        self.gridLayout_3.addWidget(self.btn_open_auto_video, 2, 0, 1, 1)
        self.label_raw_video_path = QtWidgets.QLabel(self.centralwidget)
        self.label_raw_video_path.setObjectName("label_raw_video_path")
        self.gridLayout_3.addWidget(self.label_raw_video_path, 0, 1, 1, 1)
        self.label_auto_video_path = QtWidgets.QLabel(self.centralwidget)
        self.label_auto_video_path.setObjectName("label_auto_video_path")
        self.gridLayout_3.addWidget(self.label_auto_video_path, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        manual.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(manual)
        self.statusbar.setObjectName("statusbar")
        manual.setStatusBar(self.statusbar)

        self.retranslateUi(manual)
        QtCore.QMetaObject.connectSlotsByName(manual)

    def retranslateUi(self, manual):
        _translate = QtCore.QCoreApplication.translate
        manual.setWindowTitle(_translate("manual", "人工确认"))
        self.btn_play.setText(_translate("manual", "播放"))
        self.btn_unmark.setText(_translate("manual", "取消标记"))
        self.btn_save.setText(_translate("manual", "录制"))
        self.btn_mark.setText(_translate("manual", "标记"))
        self.btn_unsave.setText(_translate("manual", "导出视频"))
        self.btn_open_raw_video.setText(_translate("manual", "打开原视频"))
        self.btn_open_auto_video.setText(_translate("manual", "打开标记视频"))
        self.label_raw_video_path.setText(_translate("manual", "null"))
        self.label_auto_video_path.setText(_translate("manual", "null"))
